version: 0.2

env:
  variables:
    ECR_REGISTRY: public.ecr.aws/r5c3t5z5
    ECR_REPO_NAME: flo2cash_exercise

phases: 
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - ./scripts/update_aws_cli.sh
  pre_build:
    commands:
      - echo $CURRENT_BRANCH 
      # we just want to push to ECR changes in master branch, in all other branches we just build the image to run tests
      - |
          if [ "$CURRENT_BRANCH" == "master" ]; then
            aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REGISTRY
          fi
  build:
    commands:
      - ./scripts/manage_images.sh
  post_build:
    commands:
      - ./scripts/create_image_definition_file.sh

artifacts:
  files:
    # archive the only file necessary for ECS to deploy the new container
    - "imagedefinitions.json"
  discard-paths: no # to keep directory structure
  name: flo2cash-build-artifact # artifact name
