version: 0.2

# env:
#   parameter-store:
#     DOCKER_ID: "/maxipaolucci/dockerID"
#     DOCKER_PASSWORD: "/maxipaolucci/dockerPassword"

phases: 
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # - printenv
      - echo "installing something"
  pre_build:
    commands: 
      - echo "we are in the pre build phase"
  build:
    commands:
      - echo $CURRENT_BRANCH
      - ./manage_images.sh
  post_build:
    commands:
      - create_image_definition_file.sh

artifacts:
  files:
    # archive the only file necessary for elastikbeanstalk to redeploy the new docker images pushed
    - "imagedefinitions.json"
  discard-paths: no # to keep directory structure
  name: flo2cash-build-artifact # this name seems to be completely ignored when codepipeline orchastrates this build
